global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"

  - job_name: "metgen"
    static_configs:
      - targets:
          - "localhost:8000"
          - "localhost:8001"
        labels:
          env: "prod"
      - targets:
          - "localhost:8002"
        labels:
          env: "dev"

  - job_name: "node"
    static_configs:
      - targets:
          - "localhost:9100"

  - job_name: "consul"
    consul_sd_configs:
      - server: "consul.lab0.sikademo.com:8500"
        tags:
          - prometheus
    relabel_configs:
      - source_labels: [__meta_consul_service]
        target_label: job
      - source_labels:
          - __meta_consul_service_address
        target_label: instance

  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module:
        - http_2xx
    static_configs:
      - targets:
          - https://ondrej-sika.cz
          - https://sika.int
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: lab0.sikademo.com:9115

  - job_name: pushgateway
    static_configs:
      - targets:
          - 127.0.0.1:9091

rule_files:
  - "prometheus.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "localhost:9093"