groups:
  - name: node
    rules:
      - alert: HighCPU
        expr: cpu_usage_perc > 80
        for: 20s
        labels:
          severity: medium
        annotations:
          summary: "High CPU usage on node {{ $labels.instance }}"
          description:  "High CPU usage on node {{ $labels.instance }}"


  - name: am-demo
    rules:
      - alert: example
        expr: probe_success{exported_instance="demo",exported_job="demo"} == 0
        for: 0s
        labels:
          severity: critical
        annotations:
          summary: "{{ $labels.app }} is down"
          description: "{{ $labels.app }} has been down for more than 20 seconds."


  - name: up
    rules:
      - alert: Up
        expr: up == 0
        for: 20s
        labels:
          level: medium
        annotations:
          summary: "Prometheus job {{ $labels.job }} with {{ $labels.instance }} instance is down"
          description: "Job {{ $labels.job }} with {{ $labels.instance }} instance has been down for more than 20 seconds."

  - name: my_vectors
    rules:
      - record: cpu_usage_perc
        expr: 100 * (1 - avg(rate(node_cpu_seconds_total{mode="idle"}[1m])) by (instance))
      - record: mem_usage_perc
        expr: 100 * (node_memory_Active_bytes / on (instance) node_memory_MemTotal_bytes)
      - record: disk_usage_perc
        expr: 100 * (1 - (node_filesystem_avail_bytes{fstype!~"tmpfs|fuse.lxcfs|squashfs|vfat"} / node_filesystem_size_bytes{fstype!~"tmpfs|fuse.lxcfs|squashfs|vfat"}))
      - record: disk_usage_perc_in_1h
        expr: 100 * (1 - (predict_linear(node_filesystem_avail_bytes{fstype!~"tmpfs|fuse.lxcfs|squashfs|vfat"}[10m], 3600) / node_filesystem_size_bytes{fstype!~"tmpfs|fuse.lxcfs|squashfs|vfat"}))
      - record: disk_usage_perc_in_4h
        expr: 100 * (1 - (predict_linear(node_filesystem_avail_bytes{fstype!~"tmpfs|fuse.lxcfs|squashfs|vfat"}[10m], 4*3600) / node_filesystem_size_bytes{fstype!~"tmpfs|fuse.lxcfs|squashfs|vfat"}))
      - record: net_kbps
        expr: sum(rate(node_network_transmit_bytes_total{device=~"eth.*|enp.*"}[10m])) by (instance)